app:
  build: .
  volumes:
     - .:/code
  links:
     - postgres
     - redis
     - mongo
  ports:
    - "8899:8899"

redis:
  build: ./redis
  ports:
    - "6379:6379"

mongo:
  image: mongo
  ports:
    - "27017:27017"

postgres:
  restart: always
  image: postgres:9.6
  ports:
    - "5432:5432"
  environment:
#    POSTGRES_USER: "dbuser"
    POSTGRES_PASSWORD: "torestpw"
#    POSTGRES_DB: "torest"
  volumes:
    - pgdata:/var/lib/postgresql/data/

#mysql:
#  image: mysql:5.6
#  environment:
#    MYSQL_ROOT_PASSWORD: its_a_secret_to_everybody
#    MYSQL_USER: qingman
#    MYSQL_PASSWORD: q1ngman
#    MYSQL_DATABASE: qingmandb
#  ports:
#    - "3306:3306"

